version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: techsecure_db
    environment:
      MYSQL_ROOT_PASSWORD: root_secure_password
      MYSQL_DATABASE: techsecure_db
    volumes:
      # Initialisation automatique de la BDD via un script SQL
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - secure_network

  web:
    build: .
    container_name: techsecure_web
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root_secure_password
      - DB_NAME=techsecure_db
    depends_on:
      - db
    networks:
      - secure_network

networks:
  secure_network:
    driver: bridge